; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "HomeAgent"
!define PRODUCT_VERSION "0.1"
!define PRODUCT_PUBLISHER "i-Housekeeping, Inc."
!define PRODUCT_WEB_SITE "http://www.i-housekeeping.co.cc"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\homeagent.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

;Define Environment variables
!define HOMEAGENT_PATH "$INSTDIR\db\homeagent.db"

; MUI 1.67 compatible ------
!include "MUI2.nsh"
!define ALL_USERS
!include WriteEnvStr.nsh # or the name you chose

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\kfm_home.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\orange-install-nsis.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_BITMAP "${NSISDIR}\Contrib\Graphics\Header\orange.bmp" ; optional
!define MUI_HEADERIMAGE_UNBITMAP "${NSISDIR}\Contrib\Graphics\Header\orange-uninstall.bmp" ; optional

!define MUI_PAGE_HEADER_TEXT "HomeAgent - installation wizard"

; Welcome page
!define MUI_WELCOMEPAGE_TITLE "Welcome to HomeAgent Setup Wizard"
!define MUI_WELCOMEPAGE_TEXT "Thank you for choosing the i-housekeeping software."
!define MUI_WELCOMEFINISHPAGE_BITMAP "${NSISDIR}\Contrib\Graphics\Wizard\arrow.bmp"
!insertmacro MUI_PAGE_WELCOME

; License page
!insertmacro MUI_PAGE_LICENSE "LICENSE"

; Directory page
!insertmacro MUI_PAGE_DIRECTORY

; Instfiles page
!insertmacro MUI_PAGE_INSTFILES

; Finish page
!define MUI_FINISHPAGE_TITLE "Thank you."
!define MUI_FINISHPAGE_TEXT "Thank you for choosing the i-housekeeping software."
!define MUI_FINISHPAGE_RUN "$INSTDIR\homeagent.exe"
!insertmacro MUI_PAGE_FINISH



; Uninstaller pages
!define MUI_UNWELCOMEFINISHPAGE_BITMAP "${NSISDIR}\Contrib\Graphics\Wizard\arrow.bmp"
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "French"
!insertmacro MUI_LANGUAGE "German"
!insertmacro MUI_LANGUAGE "Hebrew"
!insertmacro MUI_LANGUAGE "Italian"
!insertmacro MUI_LANGUAGE "Japanese"
!insertmacro MUI_LANGUAGE "Russian"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "homeagentsetup.exe"
InstallDir "$PROGRAMFILES\HomeAgent"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

XPStyle on

Function .onInit
	# the plugins dir is automatically deleted when the installer exits
	InitPluginsDir
	File /oname=$PLUGINSDIR\splash.bmp "${NSISDIR}\Contrib\Graphics\Wizard\housekeeping.bmp"
	#optional
	#File /oname=$PLUGINSDIR\splash.wav "C:\myprog\sound.wav"
        
	splash::show 2000 $PLUGINSDIR\splash

	Pop $0 ; $0 has '1' if the user closed the splash screen early,
			; '0' if everything closed normal

        ;!insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Section "MainSection" SEC01
        SetOutPath "$INSTDIR\config"
        SetOverwrite try
        File "..\myhomeagent\config\environment.yml"
        SetOutPath "$INSTDIR\db"
        File "..\myhomeagent\db\homeagent.db"
        SetOutPath "$INSTDIR"
        File "..\myhomeagent\homeagent.exe"
        CreateDirectory "$SMPROGRAMS\HomeAgent"
        CreateShortCut "$SMPROGRAMS\HomeAgent\HomeAgent.lnk" "$INSTDIR\homeagent.exe"
        CreateShortCut "$DESKTOP\HomeAgent.lnk" "$INSTDIR\homeagent.exe"
SectionEnd

Section -AdditionalIcons
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\HomeAgent\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\HomeAgent\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\homeagent.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\homeagent.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
  
  !ifdef ALL_USERS
    !define ReadEnvStr_RegKey \
       'HKLM "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"'
  !else
    !define ReadEnvStr_RegKey 'HKCU "Environment"'
  !endif


  # insert the variable
  Push "HOMEAGENT_PATH"
  Push '${HOMEAGENT_PATH}'  # value
  Call WriteEnvStr

SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) was successfully removed from your computer."
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Are you sure you want to completely remove $(^Name) and all of its components?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\homeagent.exe"
  Delete "$INSTDIR\db\homeagent.db"
  Delete "$INSTDIR\config\environment.yml"

  Delete "$SMPROGRAMS\HomeAgent\Uninstall.lnk"
  Delete "$SMPROGRAMS\HomeAgent\Website.lnk"
  Delete "$DESKTOP\HomeAgent.lnk"
  Delete "$SMPROGRAMS\HomeAgent\HomeAgent.lnk"

  RMDir "$SMPROGRAMS\HomeAgent"
  RMDir "$INSTDIR\db"
  RMDir "$INSTDIR\config"
  RMDir "$INSTDIR"

  # remove the variable
  Push "HOMEAGENT_PATH"
  Call un.DeleteEnvStr


  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd